Fixing allPossibleMigStrategiesAreNone helm chart helper.
NVIDIA/k8s-device-plugin pull request #675
Opened 2024-04-22 22:43 UTC by jakubkrzykowski

`configMapName` is the empty string `""` by default and it breaks `allPossibleMigStrategiesAreNone` function with default values.

See https://github.com/NVIDIA/k8s-device-plugin/issues/670 for details.

2024-05-23 15:00 UTC, elezar reviewed
Sorry, these were pendings.

2024-05-31 13:48 UTC, elezar requested changes

2024-05-31 13:48 UTC, elezar commented on deployments/helm/nvidia-device-plugin/templates/_helpers.tpl
> +{{- else if ne (include "nvidia-device-plugin.configMapName" .) "" -}}
Let's use the following instead:
```suggestion
{{- else if eq (include "nvidia-device-plugin.hasConfigMap" .) "true" -}}
```

2024-06-04 12:06 UTC, elezar approved these changes
Thanks @jakubkrzykowski. These look good now.

I rebased and incorporated the changes from #749

2024-06-05 09:50 UTC, merged

2024-12-19 06:22 UTC, adammw commented
having problems with this using the built in config.map option - since a configMapName is set it immediately goes to `$result = false` instead of falling through to evaluate the config.map profiles