add warning when set memory limits check is pre-volta arch
NVIDIA/k8s-device-plugin pull request #797
Opened 2024-07-01 13:54 UTC by lengrongfu

Fixes: https://github.com/NVIDIA/k8s-device-plugin/issues/647#issuecomment-2124122930

2024-07-09 09:30 UTC, elezar requested changes
Please update the warning shown as indicated.

Note that this does mean that there will be NO memory limits applied for pre-volta devices. Please update the commit message to indicate this too.

2024-07-09 09:30 UTC, elezar commented on cmd/mps-control-daemon/mps/daemon.go
> +			klog.Warningf("Device uuid %s is pre-volta arch, canno't set memory limits.", device.ID)
```suggestion
			klog.Warningf("Skipping memory limits for pre-volta device %s", device.ID)
```

2024-10-01 02:24 UTC, lengrongfu commented
OK

2024-10-02 16:43 UTC, lengrongfu commented
@elezar PTAL

2025-02-01 04:27 UTC, closed without merging