fix: remove namespace field from cluster-scoped `ClusterRole` and `ClusterRoleBinding` resources
NVIDIA/k8s-device-plugin pull request #952
Opened 2024-09-09 08:51 UTC by alfredkrohmer

2024-09-25 10:34 UTC, elezar submitted a review, later dismissed
Thanks @alfredkrohmer.

LGTM.

2024-09-25 10:40 UTC, elezar requested changes
Thanks @alfredkrohmer 

Please rebase off `main` and update the commit message to:

```
Remove namespace field from cluster-scoped resources

This changes removes the namespace field from the ClusterRole and ClusterRoleBinding
resources. Since these are culster-scoped, they are not namespaced.

See:
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrole-example
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/#clusterrolebinding-example
```

(I tried to do this myself, but I don't have push permissions on your fork).

2024-09-25 14:03 UTC, alfredkrohmer commented
@elezar Done.

2024-10-15 15:16 UTC, elezar approved these changes

2024-10-17 14:51 UTC, merged